name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-image:latest .

      - name: Save Docker image as tar file
        run: |
          docker save -o my-image.tar my-image:latest

      - name: Upload Docker image as artifact (v4)
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: my-image.tar
