name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Save Docker Image with Cached Layers
        uses: docker/build-push-action@v4
        with:
          tags: my-image:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save Docker image as tar file
        run: |
          docker save -o my-image.tar my-image:latest

      - name: Upload Docker image as artifact (v4)
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: my-image.tar
